apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocdui-route
spec:
  parentRefs:
    - name: gateway
      namespace: default
  #hostnames:
  #  - "argocd.k8s.local"
  rules:
    - backendRefs:
      - name: argocd-server
        port: 80
