image:
  tag: "sha-8cbefb1362f0efad0df5de41cafb0120d4ddd93f"
route:
  hostnames:
    - user-service.app.local
extraEnv:
  - name: SPRING_PROFILES_ACTIVE
    value: k8s-local
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgresql.postgresql:5432/users_service
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: user-service-secret
        key: spring_datasource_username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: user-service-secret
        key: spring_datasource_password
  - name: REDIS_HOST
    value: redis-master.redis
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: user-service-secret
        key: redis_cache_access_key
