apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-route
spec:
  parentRefs:
    - name: gateway
      namespace: default
  rules:
    - backendRefs:
        - name: keycloak
          port: 8080
