apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: rate-limit-200-min
  namespace: {{ .Values.ingress.gateway.namespace | default "default" }}
  annotations:
    kubernetes.io/ingress.class: kong
config:
  minute: 200
  policy: local
plugin: rate-limiting

---

apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: proxy-cache-all-endpoints-get-head
  namespace: {{ .Values.ingress.gateway.namespace | default "default" }}
  annotations:
    kubernetes.io/ingress.class: kong
plugin: proxy-cache
config:
  response_code:
    - 200
  request_method:
    - GET
    - HEAD
  content_type:
    - text/plain; charset=utf-8
  cache_ttl: 300
  strategy: memory
