apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-infrastructure
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/envs/local
    repoURL: https://github.com/mandraghen/k8s-infrastructure.git
    targetRevision: main
  syncPolicy:
    automated: { }
