apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
spec:
  encryptedData:
    password: AgCQQSYxXvSC8do+oL/IhJ072IarRYyBbhM72Vgr/zZ7I0+v7GN/X2oTiQ/FwwoDOymE+dQ1p/5LuCXNPRmuPnoTirHpLBERYXgECgMT//AXl9UACqbzsbvUGNP4NzCL2g+Vqo9uahOurGh7cBlfgR+Vaj8pUn5k8KZoLxK/6dw3vdWWugks9Y3IjB1HES53KBaXTPNUtm3FJcARQttT9RGCt5MstjqKSxMcDtP5wVM+oEau/OGGh+3JSJK6OwCo8yxFEQjEF7rYGCmIhio4xdWxFEiMSDoo521qwjd1aAnlUiYrHsnUCNhidtn4zKZXr2ZrLV2/8xB1RE6cKhv3pO5x63nDMN3OH3FPPfEFQwv9i5Hu1azyxvGE2dHgJcfempqIyoJUyL3Z0fzmxhjm5pot/Eaz4fQ5+YqvU4eqU3rj1ECcTTKQD13GtalEuV8D0s39lgwxfvyz4ECw3yO4w046MLfb/JdOFklTJ2LAD7mMuaO+093EYnOurw+mAlCRZ5/vqxuBCR/xOmEpOLSBWhRUfECM4VmPrBqQds7AT+p5lnGOy9RYqBJfFnHF8NYxJZk0zTh4JoyVN1/0oaWquiCAwgQokGqF+IljiDqX1gvDJSUa7iMd3VlKDMnZrnZ+QBWQPAqvTa8XKdIbSsx1e4UNXmVARnkSheAazdpElxxBvt0M6aIEaBaTHESR78x2elpfQQcEEkVSdAr7OHqVbA==
