image:
  tag: "sha-8680cc672321f14bc33348821037cbce38a595fb"
route:
  hostnames:
    - auth-spa.k8s.local
extraEnv:
  - name: KEYCLOAK_ID
    value: "k8s-local-web"
  - name: KEYCLOAK_REALM
    value: "demorealm"
  - name: KEYCLOAK_ISSUER
    value: "http://keycloak.keycloak:8080/realms/$KEYCLOAK_REALM"
  - name: NODE_TLS_REJECT_UNAUTHORIZED
    value: "0"
  - name: KEYCLOAK_SECRET
    valueFrom:
      secretKeyRef:
        name: auth-spa-secrets
        key: keycloak-secret
  - name: AUTH_SECRET
    valueFrom:
      secretKeyRef:
        name: auth-spa-secrets
        key: auth-secret
  - name: NEXTAUTH_URL
    value: "https://auth-spa.k8s.local:31598/"
  - name: NEXTAUTH_URL_INTERNAL
    value: "http://auth-spa.local:8039/"
