apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: postgresql
data:
  postgres-password: UGFzc3dvcmQxMjMhCg==

---

apiVersion: v1
kind: Secret
metadata:
  name: postgresql-init-user-script
  namespace: postgresql
data:
  users.sh: "IyEvYmluL2Jhc2gKc2V0IC1lCmV4cG9ydCBQR1BBU1NXT1JEPSQoY2F0IC9vcHQvYml0bmFtaS9wb3N0Z3Jlc3FsL3NlY3JldHMvcG9zdGdyZXMtcGFzc3dvcmQpCmV4cG9ydCBBUFBfREJfUEFTUz1yYW5kb20xMjMhCnBzcWwgLXYgT05fRVJST1JfU1RPUD0xIC0tdXNlcm5hbWUgcG9zdGdyZXMgPDwtRU9TUUwKICAgQ1JFQVRFIERBVEFCQVNFIGtleWNsb2FrOwogICBDUkVBVEUgVVNFUiBrZXljbG9hayBXSVRIIEVOQ1JZUFRFRCBQQVNTV09SRCAnJEFQUF9EQl9QQVNTJzsKICAgR1JBTlQgQUxMIFBSSVZJTEVHRVMgT04gREFUQUJBU0Uga2V5Y2xvYWsgVE8ga2V5Y2xvYWs7CiAgIFxjb25uZWN0IGtleWNsb2FrCiAgIEJFR0lOOwogICAgQ1JFQVRFIFNDSEVNQSBBVVRIT1JJWkFUSU9OIGtleWNsb2FrOwogICBDT01NSVQ7CkVPU1FMCgo="
