apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          env:
            - $patch: replace
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: adminUser
                  name: keycloak-secrets
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminPassword
                  name: keycloak-secrets
            - name: KC_DB
              value: postgres
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: db
            - name: KC_DB_URL
              value: jdbc:postgresql://postgresql.postgresql:5432/$(POSTGRES_DB)
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: KC_DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: KC_HEALTH_ENABLED
              value: "true"
          readinessProbe:
            initialDelaySeconds: 20
