apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          env:
            - name: KC_HOSTNAME
              value: "https://keycloak.nip.io.k8s.local:31598"
