apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-tls-redirect
spec:
  hostnames:
    - "keycloak.nip.io.k8s.local"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            port: 31598
---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-route
spec:
  hostnames:
    - "keycloak.nip.io.k8s.local"
