apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: default
spec:
  gatewayClassName: nginx
  listeners:
    - protocol: TCP
      port: 5432
      name: gateway-postgresql
      allowedRoutes:
        namespaces:
          from: All
