postgresql:
  auth:
    enablePostgresUser: true
    existingSecret: postgresql-secret
    secretKeys:
      adminPasswordKey: postgres-password
    usePasswordFiles: true
  primary:
    initdb:
      scriptsConfigMap: postgresql-init-user-script
    extraEnvVarsSecret: users-secret

  namespaceOverride: "postgresql"

  image:
    debug: true
