postgresql:
  auth:
    enablePostgresUser: true
    existingSecret: postgresql-secret
    secretKeys:
      adminPasswordKey: postgres-password
    usePasswordFiles: true
  primary:
    initdb:
      scriptsSecret: postgresql-init-user-script
    extraEnvVarsSecret: keycloak-secret

  namespaceOverride: "postgresql"

  image:
    debug: true
